#367 Optimise Dependencies
reactiveui/Fusillade pull request #370
Opened 2024-04-30 03:17 UTC by thompson-tomo

**What kind of change does this PR introduce?**
update

**What is the current behavior?**
Packages are the same for all TFM's

**What is the new behavior?**
Less dependencies are included for net 6+ due to them being available as part of the framework

**What might this PR break?**
n/a

**Other information**:
closes #367

2024-04-30 14:03 UTC, ChrisPulman requested changes

2024-04-30 14:03 UTC, ChrisPulman commented on src/Fusillade/Fusillade.csproj
> +	</ItemGroup>
Please remove this section

2024-04-30 14:03 UTC, ChrisPulman commented on src/Fusillade/Fusillade.csproj
>  		<PackageReference Include="System.Reactive" Version="6.0.0" />
Please remove this reference

2024-05-02 01:56 UTC, thompson-tomo commented on src/Fusillade/Fusillade.csproj
> +	</ItemGroup>
done

2024-05-02 01:57 UTC, thompson-tomo commented on src/Fusillade/Fusillade.csproj
>  		<PackageReference Include="System.Reactive" Version="6.0.0" />
done.

2024-05-02 01:58 UTC, thompson-tomo commented
Have made requested changes

2024-05-02 02:53 UTC, ChrisPulman approved these changes

2024-05-02 02:53 UTC, merged